# Generated by Django 2.2.5 on 2019-12-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='登录名')),
                ('name', models.CharField(max_length=10, verbose_name='真实姓名')),
                ('card_type', models.SmallIntegerField(choices=[(0, '内地居民身份证'), (1, '港澳居民身份证'), (2, '护照')], verbose_name='证件类型')),
                ('card_id', models.CharField(max_length=20, verbose_name='证件号码')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('auth_type', models.SmallIntegerField(choices=[(0, '手机'), (1, '邮箱')], verbose_name='验证方式')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='user_img/', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户是否激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='账户是否后台管理员')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
